name: Update Autoexec

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (00:00 UTC)

  workflow_dispatch:  # Allows you to run the action manually from the GitHub UI

jobs:
  update_autoexec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run the update script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e  # Ensure the script stops on error
          python update_autoexec.py

      - name: Commit and push changes
        if: success()  # Only run if the previous step was successful
        run: |
          git config --global user.name "${{ secrets.USER_NAME}}"
          git config user.email ${{ secrets.USER_EMAIL }}
          git add bindings.cfg
          git commit -m "Update bindings.cfg with new key binds" || echo "No changes to commit"
          git push
